version: '3'

volumes:
  bitcoind_datadir: /data/bitcoind-data
  clightning_bitcoin_datadir: /data/clightning-bitcoind-data

services:

  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        whitelist=0.0.0.0/0
        rpcport=43782
        server=1
        rpcuser=bitcoinrpc
        rpcpassword=rpcpassword
    volumes:
      - "bitcoind_datadir:/data"

  clightning_bitcoin:
    image: nicolasdorier/clightning
    environment:
      EXPOSE_TCP: "true"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/data/bitcoind
        bitcoin-rpcuser=bitcoinrpc
        bitcoin-rpcpassword=rpcpassword
        bitcoin-rpcconnect=bitcoind
        network=mainnet
        alias=myawesomenode
        chain=btc
    ports:
      - "9735:9735"
    volumes:
      - "clightning_bitcoin_datadir:/root/.lightning"
      - "bitcoind_datadir:/data/bitcoind"
    links:
      - bitcoind

  admin:
    image: analogic/clightning-admin
    ports:
      - "5080:80"
    environment:
      - CLIGHTNING_RPC_SOCKET=tcp://clightning_bitcoin:9835
      - BITCOIND_RPC_DSN=http://bitcoinrpc:rpcpassword@bitcoind:43782
      - PASSWORD=admin
      - APP_ENV=dev
      - SESSION_NAME=clightning
    links:
      - bitcoind
      - clightning_bitcoin

