version: '3'

volumes:
  bitcoin_datadir:
  clightning_bitcoin_datadir:

services:

  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.16.3
    container_name: bitcoind
    environment:
      BITCOIN_EXTRA_ARGS: |
        testnet=1
        whitelist=0.0.0.0/0
        server=1
        rpcuser=rpcuser
        rpcpassword=rpcpass
    expose:
      - "18332"
    ports:
      - "0.0.0.0:18333:18333"
    volumes:
      - "bitcoin_datadir:/data"

  clightning_bitcoin:
    image: elementsproject/lightningd
    container_name: lightningd
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=rpcuser
      - --bitcoin-rpcpassword=rpcpass
      - --network=testnet
      - --alias=myawesomenode
      - --log-level=debug
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9735:9735"
    volumes:
      - "clightning_bitcoin_datadir:/root/.lightning"
      - "bitcoin_datadir:/etc/bitcoin"
    links:
      - bitcoind

  admin:
    image: analogic/clightning-admin
    volumes:
      - .:/var/www
    ports:
      - "5080:80"
    environment:
      - CLIGHTNING_RPC_SOCKET=tcp://clightning_bitcoin:9835
      - BITCOIND_RPC_DSN=http://bitcoinrpc:rpcpassword@bitcoind:43782
      - PASSWORD=admin
      - APP_ENV=dev
      - SESSION_NAME=clightning1
    links:
      - bitcoind
      - clightning_bitcoin

