version: '3'

volumes:
  network-data:

services:

  admin1:
    build: .
    ports:
      - "5080:80"
    volumes:
      - network-data:/data
      - .:/var/www
    environment:
      - CLIGHTNING_RPC_SOCKET=unix:///data/lightning-1/rpc
      - BITCOIND_RPC_DSN=http://bitcoinrpc:rpcpassword@regnet:18332
      - PASSWORD=admin
      - APP_ENV=dev
      - SESSION_NAME=clightning1

  admin2:
    build: .
    ports:
      - "5081:80"
    volumes:
      - network-data:/data
      - .:/var/www
    environment:
      - CLIGHTNING_RPC_SOCKET=unix:///data/lightning-2/rpc
      - BITCOIND_RPC_DSN=http://bitcoinrpc:rpcpassword@regnet:18334
      - PASSWORD=admin
      - APP_ENV=dev
      - SESSION_NAME=clightning2

  regnet:
    image: analogic/clightning-regnet
    volumes:
      - network-data:/data