#!/usr/bin/with-contenv bash

#
# since admin runs as nobody and clightning creates socket with rights only to root, we need to fix that
#

if [[ $CLIGHTNING_RPC_SOCKET != unix* ]]; then
    s6-svc -d /var/run/s6/services/perms-fixer
    exit 0;
fi

SOCKET=${CLIGHTNING_RPC_SOCKET:7}
while [ 1 ]
do
    if [ -S $SOCKET ]; then
        chmod 777 $SOCKET
    fi
    sleep 1
done